apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: namg
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbGl1OTg5dC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYW1aeWIyZGpjbVZrT2xacGJtOWtibWx0TVRJelFBPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
